# .pre-commit-config.yaml — universal for modern Python projects (Linux)

ci:
  autofix_prs: true
  autoupdate_schedule: quarterly

repos:
  # --- Core hygiene / safety + large file guard ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files           # replaces jlebar/pre-commit-hooks
        args: ["--maxkb=1024"]                # 1 MB threshold

  # --- Python syntax modernization ---
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]  # set to --py311-plus if your minimum is 3.11

  # --- Fast lint + import sort + formatter (Ruff) ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff
        args: [--fix]         # auto-fix lint & imports
      - id: ruff-format       # formatter (can replace black)

  # --- (Optional) Keep Black; comment out if you rely on ruff-format only ---
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: [--line-length=100]

  # --- Static typing ---
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        files: ^src/|^tests/
        args:
          - --strict
          - --ignore-missing-imports
        additional_dependencies:
          - types-requests
          - types-setuptools

  # --- Spelling / prose ---
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [--ignore-words-list=crate,fo,nd]

  # --- Shell formatting & linting ---
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        args: [-i, "2", -ci, -bn]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: [-S, warning]

  # --- Security (basic static analysis of Python) ---
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-q, -r, src]
