[project]
name = "ai-cli-bridge"
version = "1.3.1"
requires-python = ">=3.10"
dependencies = [
  "playwright==1.48.0",
  "typer>=0.12",
  "rich>=13.7",
  "pydantic>=2.8",
  "platformdirs>=4.0",
  "orjson>=3.9"
]
[project.scripts]
ai-cli-bridge = "ai_cli_bridge.cli:app"
